spring.application.name=setup-manager-logging

# Receita Abidos Fusion
recipe.abidos.cost=400
recipe.abidos.mat.abidos=33
recipe.abidos.mat.tender=45
recipe.abidos.mat.timber=86

# Receita Superior Abidos Fusion
recipe.superior.cost=520
recipe.superior.mat.abidos=43
recipe.superior.mat.tender=59
recipe.superior.mat.timber=112
